### ISSUE TITLE
In Notepad++ v7.3.3 (32bit) I get "Failed to import" message

### ISSUE THREAD

**Issue by Constantin07** [yfuksenko/Tools#1]
Hi,

I get an error when I try to import the CloudFormation_json.xml in Notepad++ v7.3.3 (32 bit).
See attached the screenshot.

![capture](https://cloud.githubusercontent.com/assets/11664677/25695946/1ade3d1c-30ad-11e7-9546-aa70dd0542ff.JPG)

Do you know what could be the cause ?

Thanks & Regards,
Constantin

**Comment by yfuksenko** [comment]
Most likely you used "Save as" on the xml file instead of cloning the repo or copying the file content.
I tested this xml with 7.3.3 and was not able to reproduce this problem
